[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_API_URL = "your-api-url"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"